//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.11 at 02:58:17 PM EAT 
//


package com.mycompany.myapp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APIType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="APIType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CHECKOUT_AUTHORIZATION"/>
 *     &lt;enumeration value="CHECKOUT_SALE"/>
 *     &lt;enumeration value="REFUND_TRANSACTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "APIType")
@XmlEnum
public enum APIType {


    /**
     * POS CHECKOUT AUTHORIZATION
     * 
     */
    CHECKOUT_AUTHORIZATION,

    /**
     * POS CHECKOUT SALE
     * 
     */
    CHECKOUT_SALE,

    /**
     * REFUND TRANSACTION
     * 
     */
    REFUND_TRANSACTION;

    public String value() {
        return name();
    }

    public static APIType fromValue(String v) {
        return valueOf(v);
    }

}
