//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.10 at 02:27:56 PM EAT 
//


package com.mycompany.myapp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ButtonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ButtonCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="HOSTED"/>
 *     &lt;enumeration value="ENCRYPTED"/>
 *     &lt;enumeration value="CLEARTEXT"/>
 *     &lt;enumeration value="TOKEN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ButtonCodeType")
@XmlEnum
public enum ButtonCodeType {


    /**
     *  Creates Hosted Button
     * 
     */
    HOSTED,

    /**
     *  Creates Encrypted Button
     * 
     */
    ENCRYPTED,

    /**
     *  Creates Cleartext Button
     * 
     */
    CLEARTEXT,

    /**
     *  Creates Token or temporary Button
     * 
     */
    TOKEN;

    public String value() {
        return name();
    }

    public static ButtonCodeType fromValue(String v) {
        return valueOf(v);
    }

}
