//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.11 at 02:58:17 PM EAT 
//


package com.mycompany.myapp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Enhanced data for different transactions.
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;br xmlns="http://www.w3.org/2001/XMLSchema" xmlns:cc="urn:ebay:apis:CoreComponentTypes" xmlns:ebl="urn:ebay:apis:eBLBaseComponents" xmlns:ns="urn:ebay:apis:EnhancedDataTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema"/&gt;
 * </pre>
 * 
 * 
 * <p>Java class for EnhancedPaymentDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnhancedPaymentDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ebay:apis:eBLBaseComponents}AirlineItinerary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnhancedPaymentDataType", namespace = "urn:ebay:apis:EnhancedDataTypes", propOrder = {
    "airlineItinerary"
})
public class EnhancedPaymentDataType {

    @XmlElement(name = "AirlineItinerary", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected AirlineItineraryType airlineItinerary;

    /**
     * 
     *                         AID for Airlines
     *                     
     * 
     * @return
     *     possible object is
     *     {@link AirlineItineraryType }
     *     
     */
    public AirlineItineraryType getAirlineItinerary() {
        return airlineItinerary;
    }

    /**
     * Sets the value of the airlineItinerary property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirlineItineraryType }
     *     
     */
    public void setAirlineItinerary(AirlineItineraryType value) {
        this.airlineItinerary = value;
    }

}
