//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.08 at 03:44:17 PM EAT 
//


package com.mycompany.myapp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetMobileCheckoutRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetMobileCheckoutRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ebay:apis:eBLBaseComponents}AbstractRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ebay:apis:eBLBaseComponents}SetMobileCheckoutRequestDetails"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetMobileCheckoutRequestType", namespace = "urn:ebay:api:PayPalAPI", propOrder = {
    "setMobileCheckoutRequestDetails"
})
public class SetMobileCheckoutRequestType
    extends AbstractRequestType
{

    @XmlElement(name = "SetMobileCheckoutRequestDetails", namespace = "urn:ebay:apis:eBLBaseComponents", required = true)
    protected SetMobileCheckoutRequestDetailsType setMobileCheckoutRequestDetails;

    /**
     * Gets the value of the setMobileCheckoutRequestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SetMobileCheckoutRequestDetailsType }
     *     
     */
    public SetMobileCheckoutRequestDetailsType getSetMobileCheckoutRequestDetails() {
        return setMobileCheckoutRequestDetails;
    }

    /**
     * Sets the value of the setMobileCheckoutRequestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetMobileCheckoutRequestDetailsType }
     *     
     */
    public void setSetMobileCheckoutRequestDetails(SetMobileCheckoutRequestDetailsType value) {
        this.setMobileCheckoutRequestDetails = value;
    }

}
